<div>
<h2>Sign-up</h2>
<form action="/auth/do-signup/" id="single-form">
	ФИО: <input type="text" name="fio" /><br/>
	Мыло: <input type="text" name="email" /><br/>
	Пароль: <input type="password" type="password" name="password" /><br />
	Подтвердить пароль: <input type="password" type="password" name="conf_password" /><br />
	<br/>

	<div id="geo-search" style="margin-bottom: 10px;">
		<input type="button" value="Найти мой дом" />
		<div id="geo-buildings-list"></div>
	</div>

	<div id="buidling-address">
	<input type="radio" name="geo-building" checked="checked" value="0" />Улица: <select name="street">
		<option value="0">Выбрать улицу:</option>
		<?php
			foreach ($this->_params['streets'] as $key => $street):
			?>

			<option value="<?=$key?>"><?=htmlspecialchars($street)?></option>

			<?php
			endforeach;
		?>

	</select> <select name="number">
		<option value="0">Номер дома:</option>
	</select>
	</div>
	<br/>
	<br/>
	<input type="submit" value="Submit" />
</form>
</div>
<script type="text/javascript">
	$(function(){
		new Views.SignupForm('<?=_url('/auth/signin/');?>');
		new Views.StreetNumbersLoader();
		new Views.GeoSearch();
	})
</script>