<div>
	<h2>Переписки</h2>
	<div>
		<div style="float: left; width: 75%;" id="dialog-io">
			<div style="padding: 5px;">
				<div style="height: 300px; background-color: #F4F2F2; margin-bottom: 10px; padding: 5px; overflow: auto;" id="dialog-output">

				</div>
				<div id="dialog-input">
					<textarea style="width: 100%; height: 70px;"></textarea>
					<div style="text-align: right; margin-top:5px;">
						<input type="submit" value="Отправить" name="send"/>
					</div>
				</div>
			</div>
		</div>
		<div style="float: right; width: 25%;" id="dialogs-list">
			<div style="padding: 5px; overflow: auto; height: 300px;">
				<?php
					foreach ($this->_params['dialogs_list'] as $item)
					{
						$this->block('messages/contact.phtml', $item);
					}
				?>
			</div>
		</div>
		<br class="clr" />
	</div>
</div>
<script type="text/javascript">
	$(function(){
		new Views.DialogsList(<?=$this->_params['active_user_id']?>);
		Views.DialogIO.getInstance();
	});
</script>
