<div>
	<h2>Переписки</h2>
	<div>
		<div style="float: left; width: 75%;">
			<div style="padding: 5px;">
				<div style="height: 300px; background-color: #F4F2F2; margin-bottom: 10px; padding: 5px; overflow: auto;">
					<?php
						for ($i=0; $i <=10; $i++)
						{
							$this->block('messages/item.phtml');
						}
					?>
				</div>
				<div>
					<textarea style="width: 100%; height: 70px;"></textarea>
					<div style="text-align: right; margin-top:5px;">
						<input type="submit" value="Отправить" />
					</div>
				</div>
			</div>
		</div>
		<div style="float: right; width: 25%;">
			<div style="padding: 5px; overflow: auto; height: 300px;" id="dialogs-list">
				<?php
					foreach ($this->_params['dialogs_list'] as $item)
					{
						$this->block('messages/contact.phtml', $item);
					}
				?>
			</div>
		</div>
		<br class="clr" />
	</div>
</div>
<script type="text/javascript">

</script>
