<div style="background-color: #FBFBFB; border: 1px solid #999999; margin-bottom: 20px;">
	<div style="padding: 5px; padding-bottom: 15px;">
		<div><a href="#">Igor Vorobioff</a></div>
		<h3 style="color: red">Проблема</h3>
		<div>Незадачливый водитель неудачно свернул налево. В результате автомобиль столкнулся со встречной машиной. Инцидент произошел на одной из столичных улиц в секторе Чеканы.</div>
	</div>
</div>