<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link type="text/css" href="/front/css/styles.css" rel="stylesheet" />
<script src="/front/js/jquery.js"></script>
<script src="/front/js/class.js"></script>
<script src="/front/js/underscore-min.js"></script>
<script src="/front/js/main.js"></script>
<title><?=$this->_params['title']?></title>
</head>
<body>
	<?php if(is_auth()):?>
	<a href="<?=_url('/auth/logout/')?>">Logout</a>
	<br/>
	<?php endif;?>
	<?=$this->view()?>
</body>
</html>