<select>
	<option value="<?=$this->_params['current_building_id']?>"><?=$this->_params['current_building_address']?></option>
</select>
<?php
	$menu_items[] = array(
		'url' => _url('/discussions/index/'),
		'title' => 'Дискуссии'
	);

	$menu_items[] = array(
		'url' => _url('/neighbors/index/'),
		'title' => 'Соседи'
	);

	$menu_items[] = array(
		'url' => _url('/auth/logout/'),
		'title' => 'Выйти'
	);

	Views_Helpers_Menu::drawHeaderMenu($menu_items);
?>
