<div>
<h2>Sign-up</h2>
<form action="/users/do-signup/" id="signup-form">
	ФИО: <input type="text" name="fio" /><br/>
	Мыло: <input type="text" name="email" /><br/>
	Пароль: <input type="password" type="password" name="password" /><br />
	Подтвердить пароль: <input type="password" type="password" name="conf_password" />
	<br />
	<input type="submit" value="Submit" />
</form>
</div>
<script type="text/javascript">
	$(function(){
		new Views.SignupForm();
	})
</script>