<div>
	<h2>Мой двор</h2>
	<div>
		<h3>Дома в вашем дворе</h3>
	<div id="buildings-container">
	<?php
		foreach ($this->_params['buildings_list'] as $item)
		{
			$this->block('courtyards/item.phtml', $item);
		}
	?>
	</div>
		<div style="margin-bottom: 10px; position: relative;" id="courtyard-suggestions-list">
			<h3>Рекомендуемые дома</h3>
			<?php
				foreach ($this->_params['suggestions_list'] as $item)
				{
					$this->block('courtyards/suggestion.phtml', $item);
				}
			?>
			<div id="suggestions-disabler" style="position: absolute; top: 0; left: 0; opacity: 0.5; width: 100%; height: 100%; background-color: #ffffff; display: none;"></div>
		</div>
		<h3>Найти вручную</h3>
		<div style="margin-bottom: 20px;">
		<form action="/courtyards/add-building" id="single-form">
			<span  id="buidling-address">
			<select name="street">
			<option value="0">Выбрать улицу:</option>
			<?php
				foreach ($this->_params['streets'] as $key => $street):
				?>

				<option value="<?=$key?>"><?=htmlspecialchars($street)?></option>

				<?php
				endforeach;
			?>
			</select>
			<select name="number">
				<option value="0">Номер дома:</option>
			</select>
			</span>
			&nbsp;&nbsp;&nbsp;
			<input type="submit" value="Добавить дом" />
		</form>
		</div>
	</div>
</div>
<script>
$(function(){
	new Views.CourtyardForm();
	new Views.StreetNumbersLoader();
	new Views.CourtyardSuggestions();
});
</script>